{% set version = "1" %}

package:
  name: _numpy_rc
  version: {{ version }}

build:
  number: 0
  noarch: generic

test:
  commands:
  - echo "Keep conda-smithy happy."

about:
  home: https://github.com/conda-forge/_numpy_rc-feedstock
  summary: 'Dummy package to force selection of numpy_rc channel when channel_priority is set to strict'
  description: 'See https://github.com/conda-forge/conda-forge-ci-setup-feedstock/issues/280'
  license: Unlicense

extra:
  recipe-maintainers:
    - h-vetinari
    - conda-forge/numpy
